kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.makerforce.io
    repo: registry.makerforce.io/ambrose/file-manager
    tags:
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: docker-env
  image: plugins/docker
  settings:
    registry: registry.makerforce.io
    repo: registry.makerforce.io/ambrose/file-manager
    dockerfile: Dockerfile.env
    tags:
    - env
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: docker-pwn
  image: plugins/docker
  settings:
    registry: registry.makerforce.io
    repo: registry.makerforce.io/ambrose/file-manager
    dockerfile: Dockerfile.pwn
    tags:
    - pwn
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ failure, success ]
